export const Routes = {
    profile: '/profile',
    profileEdit: '/profile/edit',
    myItems: '/profile/items/my',
    myItem: '/profile/items/:id',
    login: '/login',
    cart: '/cart',
    checkout: '/checkout',
    shop: '/shop',
    news: '/news',
    main: '/',
    nftDrop: '/nft-drop',
    team: '/team',
    productPage: '/product/:id',
    howItWorks: '/how-it-works',
    ownToEarn: '/how-to-earn',
    whitePaper: '/white-paper',
    sustainability: '/sustainability',
    termsOfService: '/terms-of-service',
    privacy: '/privacy-policy',
    authCallback: '/oauth/callback'
};